servinow_factura:
    resource: "@ServinowFacturaBundle/Resources/config/routing.yml"
    prefix:   /

servinow_movimientos_de_caja:
    resource: "@ServinowMovimientosDeCajaBundle/Resources/config/routing.yml"
    prefix:   /{restaurantID}/caja

servinow_navigation:
    resource: "@ServinowNavigationBundle/Resources/config/routing.yml"
    prefix:   /{restaurantID}/

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
